#.travis.yml

language: node_js
node_js:
  - "6.9"

branches:
  only:
    - master

before_script:
  - npm install -g gulp-cli
  - npm install -g bower
  - bower install

script:
  - gulp build

after_success:

notifications:
  email:
    on_failure: change
    on_success: change
